### ISSUE TITLE
some festivals seems to be missing

### ISSUE THREAD

**Issue by pulkit10251** [Raj9039852537/Shri-Jagannath-Panchang#5]
This issue is particularly raised for Makar sakranti and Holi which is not available, also I am little bit confused the website is showing the sankranti for 4 Jan 2022 as 15 Dec 2021, but shouldn't it be 14 Jan 2022 ?

**Comment by Raj9039852537** [comment]
As for makar samkranti issue.
when you look closely you can see that just above this line saurmasa is given and for that saurmasa the samkranti is happened on the given day. So what it told is the actual occurance of samkranti for the current saurmasa.
When you change date to 15 January it gives you the time for Makar Samkranti.
for Holi not shown as festival "Holika dahan" has been listed and one day after that is "Holi/ dhulandi" which is added.
Thanks for reminding
