### ISSUE TITLE
Kundli Dosh Found(Calculator)

### ISSUE THREAD

**Issue by Bhavin213** [Raj9039852537/Shri-Jagannath-Panchang#7]
If someone has any dosha then it should be popup, for example if someone has mangal dosh then message should come that you have mangal dosh

I tried but didn't happen

In this i have to add these features

@Raj9039852537 **can you do it plz ?**
as fast as possible

**Comment by Raj9039852537** [comment]
Dosha are created and nullified by many other yogas
As for mangalik Dosha 
As per vedic jyotisha if mangal is situated in 1,4,7,8 or 12th bhava in an kundli there exist a mangalik dosha.
but there are many combinations which nullified these effects.
Those all can not be possibly incorporated in a program

It is suggested to take advice of a jyotishi instead for accuracy.
